FROM python:3.10-slim-buster

WORKDIR /app/src/

COPY src/requirements.txt .
RUN apt-get update
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt
COPY src/ ./

CMD ["python3", "main.py"]
